services:
  - type: web
    name: weather-app
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/weather-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: OPENWEATHER_API_KEY
        fromSecret: true